# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.13.2
_src_path: gh:tsvikas/python-template
format_tool: black
get_package_version_from_vcs: true
github_user: tsvikas
has_cli: false
jupyter_files: forbid
license: MIT
package_description: Convert numbers to Hebrew.
package_name: hebrew_numbers
project_name: hebrew-numbers
python_min: 9
user_email: tsvikas@gmail.com
user_name: Tsvika Shapira
year: 2025
